### ISSUE TITLE
getBlastPDB api shutdown

### ISSUE THREAD

**Issue by altingia** [LysSanzMoreta/LYS_Automatic_Search#1]
LYS_PDB_Search.py  line93: url = "http://www.rcsb.org/pdb/rest/getBlastPDB1?sequence=%s&eCutOff=1e-6&matrix=BLOSUM62" % (gene_sequence) 

 the getBlastPBD, Legacy API Shutdown, how to update with the new api?

**Comment by LysSanzMoreta** [comment]
Yeah, I would have to look into that, they have made quite some changes.

They announced the shutdown here: https://www.rcsb.org/news/5fc9176809ae2a096d081e28

I am afraid you will have to find a work around on your own for the moment. I do not have much time for this at the moment. If I get to update these scripts I would have to re-do them entirely because they require quite some improvement.

I am pretty sure there are some methods out there to `Blast again the PDB database and retrieve the homolog structure`. Once you manage to retrieve the sequences,  the rest of the script should work though (perhaps some small  pandas error or so).

**Comment by LysSanzMoreta** [comment]
@altingia I have fixed the problem with the API shutdown and everything should work again (at least it does with the example sequences). I have re-structured the entire scripts and now they run from a single file: https://github.com/LysSanzMoreta/LYS_Automatic_Search/blob/master/LYS_autosearch_example.py

By combining different options. You only need the -proteins- and -codeml-output- arguments to make it run the first time, 

I am working (slowly) on fixing the interaction between Tkinker and Pymol which makes Pymol run only in the background.

I know it is late, but I hope it might work/help someone

**Comment by LysSanzMoreta** [comment]
I have fixed the above mentioned issue as well
